config/routes.rb
Inmailing::Application.routes.draw do
  resources :positions

  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_out" => "sessions#destroy", :as => "log_out"

  resources :departments
  resources :types
  resources :mailings
  resources :users
  resources :sessions

  root to: 'welcome#index'

  get "sent" => "mailings#index", type: "sent"
  get "unsent" => "mailings#index", type: "unsent"
  get "inbox" => "mailings#index", type: "inbox"

  get "/mailings(.:format)" => "mailings#index"
  get "/mailings/:id(.:format)" => "mailings#show"

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Inmailing"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
      .navbar-header
        %button.navbar-toggle{"data-toggle" => "collapse", "data-target" => ".navbar-ex1-collapse"}
          %span.sr-only
            Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") Inmailing
      .collapse.navbar-collapse.navbar-ex1-collapse
        %ul.nav.navbar-nav
          %li= link_to "Inbox", inbox_path
          %li= link_to "Unsent", unsent_path
          %li= link_to "Sent", sent_path
          %li= link_to "Departments", departments_path
          %li= link_to "Positions", positions_path
          %li= link_to "Types", types_path
          %li= link_to "LogOut", log_out_path

    .container
      .row
        .col-lg-9
          = bootstrap_flash
      .row
        = user_and_department
      .row
        = yield
    
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/log_in.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Inmailing"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
      .navbar-header
        %a.navbar-brand(href="#") Inmailing

    .container
      .row
        = yield
    
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"